# NumPy: тренировочный ноутбук

В каждой теме 5-6 заданий. Замени `...` на свой код и запусти ячейку. Если `assert` не падает, задание решено.


In [2]:
import numpy as np

np.set_printoptions(suppress=True)


## 1. Arrays and attributes

Пример:


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)


(2, 3)
2
6


**Задание 1.** Заполни пропуски `...`, чтобы проверка прошла.


In [2]:
a1 = np.array([5, 10, 15])
assert np.array_equal(a1, np.array([5, 10, 15]))


**Задание 2.** Заполни пропуски `...`, чтобы проверка прошла.


In [4]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2.shape
assert a2.shape == (2, 3)
assert np.array_equal(a2, np.array([[1, 2, 3], [4, 5, 6]]))


(2, 3)

**Задание 3.** Заполни пропуски `...`, чтобы проверка прошла.


In [6]:
a3 = np.array([[[1], [2]], [[3], [4]]])
a3_ndim = a3.ndim
assert a3_ndim == 3


**Задание 4.** Заполни пропуски `...`, чтобы проверка прошла.


In [10]:
a4 = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])
a4_shape = a4.shape
assert a4_shape == (2, 4)


**Задание 5.** Заполни пропуски `...`, чтобы проверка прошла.


In [11]:
a5 = np.zeros((3, 4))
print(a5)
a5_size = a5.size
assert a5_size == 12


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Задание 6.** Заполни пропуски `...`, чтобы проверка прошла.


In [12]:
a6 = np.array(np.array([1.0, 2.0, 3.0]), dtype=np.float64)
assert a6.dtype == np.float64
assert np.array_equal(a6, np.array([1.0, 2.0, 3.0]))


## 2. Indexing and slicing

Пример:


In [13]:
m = np.array([[10, 11, 12, 13], [20, 21, 22, 23], [30, 31, 32, 33]])
print(m[1, 2])
print(m[:, 0])
print(m[0, 1:3])


22
[10 20 30]
[11 12]


**Задание 1.** Заполни пропуски `...`, чтобы проверка прошла.


In [15]:
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x1 = m1[2, 1]
print(x1)
assert x1 == 8


8


**Задание 2.** Заполни пропуски `...`, чтобы проверка прошла.


In [21]:
m2 = np.array([[5, 6, 7], [8, 9, 10]])
row1 = m2[0]
print(row1)
assert np.array_equal(row1, np.array([5, 6, 7]))


[5 6 7]


**Задание 3.** Заполни пропуски `...`, чтобы проверка прошла.


In [22]:
m3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
col3 = m3[:,2]
assert np.array_equal(col3, np.array([3, 6, 9]))


**Задание 4.** Заполни пропуски `...`, чтобы проверка прошла.


In [28]:
m4 = np.array([[10, 20, 30, 40, 50, 60], [1, 2, 3, 4, 5, 6]])
slice4 = m4[0,1::2]
print(slice4)
assert np.array_equal(slice4, np.array([20, 40, 60]))


[20 40 60]


**Задание 5.** Заполни пропуски `...`, чтобы проверка прошла.


In [29]:
m5 = np.array([[1, 2], [3, 4]])
m5[1,0]=100
assert m5[1, 0] == 100


**Задание 6.** Заполни пропуски `...`, чтобы проверка прошла.


In [39]:
m6 = np.array([[1, 2], [3, 4], [5, 6]])
m6[0,1]=9
m6[1,1]=8
m6[2,1]=7

assert np.array_equal(m6[:, 1], np.array([9, 8, 7]))


## 3. Creating arrays

Пример:


In [ ]:
print(np.zeros((2, 3)))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))


**Задание 1.** Заполни пропуски `...`, чтобы проверка прошла.


In [41]:
z1 = np.zeros((3,2))
assert z1.shape == (3, 2)
assert np.all(z1 == 0)


**Задание 2.** Заполни пропуски `...`, чтобы проверка прошла.


In [42]:
o2 = np.ones((2, 4))
assert o2.shape == (2, 4)
assert np.all(o2 == 1)


**Задание 3.** Заполни пропуски `...`, чтобы проверка прошла.


In [46]:
f3 = np.array([[7, 7], [7, 7]])
print(f3)
assert np.array_equal(f3, np.array([[7, 7], [7, 7]]))


[[7 7]
 [7 7]]


**Задание 4.** Заполни пропуски `...`, чтобы проверка прошла.


In [47]:
r4 = np.array([3, 6, 9, 12])
assert np.array_equal(r4, np.array([3, 6, 9, 12]))


**Задание 5.** Заполни пропуски `...`, чтобы проверка прошла.


In [48]:
l5 = np.array([10, 12.5, 15, 17.5, 20])
assert np.allclose(l5, np.array([10, 12.5, 15, 17.5, 20]))


**Задание 6.** Заполни пропуски `...`, чтобы проверка прошла.


In [49]:
eye6 = np.identity(4)
print(eye6)
assert np.array_equal(eye6, np.identity(4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 4. View, copy, fancy indexing

Пример:


In [ ]:
arr = np.array([1, 2, 3, 4])
view = arr[:2]
view[0] = 99
print(arr)


**Задание 1.** Заполни пропуски `...`, чтобы проверка прошла.


In [3]:
base1 = np.array([1, 2, 3, 4])
part1 = base1
part1[0] = 100
assert base1[0] == 100


**Задание 2.** Заполни пропуски `...`, чтобы проверка прошла.


In [4]:
base2 = np.array([1, 2, 3, 4])
part2 = base2.copy()
part2[0] = 100
assert base2[0] == 1
assert part2[0] == 100


**Задание 3.** Заполни пропуски `...`, чтобы проверка прошла.


In [6]:
base3 = np.array([10, 20, 30, 40, 50])
chosen3 = base3[::2]
print(chosen3)
assert np.array_equal(chosen3, np.array([10, 30, 50]))


[10 30 50]


**Задание 4.** Заполни пропуски `...`, чтобы проверка прошла.


In [10]:
base4 = np.array([5, 6, 7, 8])
chosen4 = base4[[3, 1, 3]]
assert np.array_equal(chosen4, np.array([8, 6, 8]))


**Задание 5.** Заполни пропуски `...`, чтобы проверка прошла.


In [12]:
mat5 = np.array([[1, 2, 3], [4, 5, 6]])
safe5 = mat5[:, 0].copy()
print(safe5)

assert mat5[1, 0] == 4
assert safe5[0] == -1


[1 4]


AssertionError: 

**Задание 6.** Заполни пропуски `...`, чтобы проверка прошла.


In [14]:
mat6 = np.array([[1, 2], [3, 4], [5, 6]])
rows6 = mat6[[2,0]]
print(rows6)
assert np.array_equal(rows6, np.array([[5, 6], [1, 2]]))


[[5 6]
 [1 2]]


## 5. Vector math

Пример:


In [ ]:
a = np.array([1, 2, 3])
print(a + 10)
print(a * 2)
print(a ** 2)


**Задание 1.** Заполни пропуски `...`, чтобы проверка прошла.


In [15]:
v1 = np.array([1, 2, 3])
res1 = v1 + 5
assert np.array_equal(res1, np.array([6, 7, 8]))


**Задание 2.** Заполни пропуски `...`, чтобы проверка прошла.


In [16]:
v2 = np.array([2, 4, 6])
res2 = v2*3
assert np.array_equal(res2, np.array([6, 12, 18]))


**Задание 3.** Заполни пропуски `...`, чтобы проверка прошла.


In [17]:
v3 = np.array([1, 3, 5])
res3 = v3 ** 2
assert np.array_equal(res3, np.array([1, 9, 25]))


**Задание 4.** Заполни пропуски `...`, чтобы проверка прошла.


In [18]:
v4a = np.array([1, 2, 3])
v4b = np.array([10, 20, 30])
res4 = v4a + v4b
assert np.array_equal(res4, np.array([11, 22, 33]))


**Задание 5.** Заполни пропуски `...`, чтобы проверка прошла.


In [ ]:
v5 = np.array([4, 9, 16])
res5 = ...
assert np.array_equal(res5, np.array([2.0, 3.0, 4.0]))


**Задание 6.** Заполни пропуски `...`, чтобы проверка прошла.


In [19]:
v6 = np.array([2, 4, 8])
res6 = res6 = v6 / v6[-1]
assert np.allclose(res6, np.array([0.25, 0.5, 1.0]))


## 6. Statistics and axis

Пример:


In [20]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(stats, axis=0))
print(np.sum(stats, axis=1))
print(np.mean(stats))


[5 7 9]
[ 6 15]
3.5


**Задание 1.** Заполни пропуски `...`, чтобы проверка прошла.


In [21]:
s1 = np.array([[9, 2, 7], [4, 5, 6]])
ans1 = np.min(s1)
assert ans1 == 2


**Задание 2.** Заполни пропуски `...`, чтобы проверка прошла.


In [22]:
s2 = np.array([[1, 8, 3], [4, 2, 9]])
ans2 = np.max(s2, axis=1)
assert np.array_equal(ans2, np.array([8, 9]))


**Задание 3.** Заполни пропуски `...`, чтобы проверка прошла.


In [23]:
s3 = np.array([[1, 2, 3], [10, 20, 30]])
ans3 = np.sum(s3, axis=0)
assert np.array_equal(ans3, np.array([11, 22, 33]))


**Задание 4.** Заполни пропуски `...`, чтобы проверка прошла.


In [5]:
s4 = np.array([[1, 2, 3], [10, 20, 30]])
ans4 = np.sum(s4,axis=1)

assert np.array_equal(ans4, np.array([6, 60]))


**Задание 5.** Заполни пропуски `...`, чтобы проверка прошла.


In [6]:
s5 = np.array([[1, 2], [3, 4]])
ans5 = np.average(s5)
assert ans5 == 2.5


**Задание 6.** Заполни пропуски `...`, чтобы проверка прошла.


In [7]:
s6 = np.array([[2, 4], [6, 8], [10, 12]])
ans6 = np.mean(s6, axis=0)
assert np.array_equal(ans6, np.array([6.0, 8.0]))


## 7. Boolean masks

Пример:


In [9]:
data = np.array([10, 20, 30, 40, 50])
print(data > 30)
print(data[data > 30])


[False False False  True  True]
[40 50]


**Задание 1.** Заполни пропуски `...`, чтобы проверка прошла.


In [10]:
d1 = np.array([10, 20, 30, 40])
ans1 = d1[d1 >= 30]
assert np.array_equal(ans1, np.array([30, 40]))


**Задание 2.** Заполни пропуски `...`, чтобы проверка прошла.


In [11]:
d2 = np.array([1, 2, 3, 4, 5, 6])
ans2 = d1[d1 >= 30]
assert np.array_equal(ans2, np.array([2, 4, 6]))


**Задание 3.** Заполни пропуски `...`, чтобы проверка прошла.


In [18]:
d3 = np.array([10, 20, 30, 40, 50, 60])
ans3 = d3[(d3 > 10) & (d3 < 60)]
print(ans3)
assert np.array_equal(ans3, np.array([20, 30, 40, 50]))


[20 30 40 50]


**Задание 4.** Заполни пропуски `...`, чтобы проверка прошла.


In [ ]:
d4 = np.array([-5, 0, 5, 10, 15])
ans4 = ...
assert np.array_equal(ans4, np.array([-5, 15]))


**Задание 5.** Заполни пропуски `...`, чтобы проверка прошла.


In [19]:
d5 = np.array([3, 4, 6, 7, 9])
mask5 = d5 % 3 == 0
assert np.array_equal(mask5, np.array([True, False, True, False, True]))


**Задание 6.** Заполни пропуски `...`, чтобы проверка прошла.


In [20]:
d6 = np.array([[1, 5, 2], [7, 3, 9]])
ans6 = d6[d6>=5]
assert np.array_equal(ans6, np.array([5, 7, 9]))


## 8. np.where

Пример:


In [21]:
data = np.array([10, 20, 30, 40])
print(np.where(data >= 30, 1, 0))


[0 0 1 1]


**Задание 1.** Заполни пропуски `...`, чтобы проверка прошла.


In [22]:
w1 = np.array([5, 10, 15, 20])
ans1 = np.where(w1 > 10, 1, 0)
assert np.array_equal(ans1, np.array([0, 0, 1, 1]))


**Задание 2.** Заполни пропуски `...`, чтобы проверка прошла.


In [25]:
w2 = np.array([-3, 2, -1, 5])
ans2 = np.where(w2 > 0, w2, 0)
assert np.array_equal(ans2, np.array([0, 2, 0, 5]))


**Задание 3.** Заполни пропуски `...`, чтобы проверка прошла.


In [ ]:
w3 = np.array([1, 2, 3, 4])
ans3 = ...
assert np.array_equal(ans3, np.array(["odd", "even", "odd", "even"]))


**Задание 4.** Заполни пропуски `...`, чтобы проверка прошла.


In [ ]:
w4 = np.array([10, 20, 30, 40])
ans4 = ...
assert np.array_equal(ans4, np.array([-1, -1, 1, 1]))


**Задание 5.** Заполни пропуски `...`, чтобы проверка прошла.


In [ ]:
w5 = np.array([0, 1, 0, 2, 3])
ans5 = ...
assert np.array_equal(ans5, np.array([100, 1, 100, 2, 3]))


**Задание 6.** Заполни пропуски `...`, чтобы проверка прошла.


In [ ]:
w6 = np.array([[1, 6, 3], [8, 2, 10]])
ans6 = ...
assert np.array_equal(ans6, np.array([[1, 5, 3], [5, 2, 5]]))


## 9. Reshape and stacking

Пример:


In [26]:
a = np.arange(1, 9)
print(a.reshape((2, 4)))
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(np.vstack([v1, v2]))
print(np.hstack([v1, v2]))


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


**Задание 1.** Заполни пропуски `...`, чтобы проверка прошла.


In [27]:
r1 = np.array([[1, 2, 3], [4, 5, 6]])
assert np.array_equal(r1, np.array([[1, 2, 3], [4, 5, 6]]))


**Задание 2.** Заполни пропуски `...`, чтобы проверка прошла.


In [32]:
r2 = np.array([[1, 2], [3, 4], [5, 6]])
flat2 = r2.reshape(6)
print(flat2)
assert np.array_equal(flat2, np.array([1, 2, 3, 4, 5, 6]))


[1 2 3 4 5 6]


**Задание 3.** Заполни пропуски `...`, чтобы проверка прошла.


In [33]:
r3 = np.arange(12)
mat3 = r3.reshape((3,4))
assert mat3.shape == (3, 4)
assert mat3[2, 3] == 11


**Задание 4.** Заполни пропуски `...`, чтобы проверка прошла.


In [35]:
v4a = np.array([1, 2, 3])
v4b = np.array([4, 5, 6])
stack4 = np.vstack([v4a,v4b])
assert np.array_equal(stack4, np.array([[1, 2, 3], [4, 5, 6]]))


**Задание 5.** Заполни пропуски `...`, чтобы проверка прошла.


In [36]:
v5a = np.array([1, 2])
v5b = np.array([3, 4])
stack5 = np.hstack([v5a,v5b])
assert np.array_equal(stack5, np.array([1, 2, 3, 4]))


**Задание 6.** Заполни пропуски `...`, чтобы проверка прошла.


In [37]:
r6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
edges6 = r6[:, [0, -1]]
assert np.array_equal(edges6, np.array([[1, 3], [4, 6], [7, 9]]))
