# Numpy

Numpy — это главная библиотека для работы с массивами и матрицами в питоне. Она написана на C, поэтому работает очень быстро. Почти вся аналитика и машинное обучение под капотом используют numpy, поэтому важно понимать как она работает.

Экстремально детальный справочник есть в EXTRA материале по numpy в этом репозитории.

Для начала библиотеку нужно импортировать. Общепринятое сокращение для неё — `np`, используйте его всегда.

In [3]:
import numpy as np

### Почему Numpy, а не обычные списки?

Главная фишка Numpy — скорость. Встроенные списки (`list`) в питоне работают медленно, когда данных много. Давайте проверим это с помощью магической команды `%%timeit`, которая замеряет время выполнения ячейки.

In [4]:
%%timeit
# Обычный питон: возводим в квадрат миллион чисел
python_list = list(range(1000000))
result = [x**2 for x in python_list]

194 ms ± 389 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%%timeit
# Numpy: делаем то же самое
numpy_array = np.arange(1000000)
result = numpy_array ** 2

1.59 ms ± 26.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Разница колоссальная (в десятки или сотни раз)! Поэтому в анализе данных мы везде используем Numpy.

### Основы

Создаём обычный одномерный `np.array` (вектор). Напомню, что в самом питоне нет массивов, есть только списки (`list`). В numpy мы работаем именно с `np.array`.

In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

А вот так двумерный (матрицу). В numpy можно задавать тип данных (например, `float64`, `int32`), чтобы контролировать сколько памяти занимает `np.array`.

In [7]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

У `np.array` есть полезные атрибуты, которые часто нужны в работе:

In [8]:
a.ndim # количество измерений (dimension)

1

In [9]:
b.shape # форма (строки, столбцы)

(2, 3)

In [10]:
a.dtype # тип данных

dtype('int32')

In [11]:
a.size # общее количество элементов

3

### Доступ и изменение элементов (индексация)

Работает похоже на обычные списки, но можно указывать индексы через запятую `[строка, колонка]`.

In [18]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

Достаём конкретный элемент (вторая строка, шестой столбец). Индексация с нуля!

In [16]:
c[1, 5]

13

Можно достать всю строку или всю колонку, используя `:` (двоеточие).

In [48]:
c[0, :] # первая строка

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
c[:, 2] # третий столбец

array([ 3, 10])

Работают и более сложные срезы `[старт : стоп : шаг]`.

In [50]:
c[0, 1:-1:2]

array([2, 4, 6])

Изменять элементы тоже легко, можно поменять одно значение, а можно сразу целую колонку.

In [51]:
c[1, 5] = 20
c[:, 2] = [1, 2]
c

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [19]:
# TODO поменяйте первый элемент во второй строке массива c на 100
c[1, 0] = 100

assert c[1, 0] == 100

### Инициализация разных `np.array`

Часто бывает нужно создать `np.array`, заполненный нулями, единицами или случайными числами. Также очень популярны `np.arange` (аналог `range`) и `np.linspace`.

In [20]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [56]:
np.arange(0, 10, 2) # от 0 до 10 (не включая) с шагом 2

array([0, 2, 4, 6, 8])

In [57]:
np.linspace(0, 1, 5) # 5 чисел, равномерно распределенных от 0 до 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [58]:
np.random.rand(4, 2) # случайные числа от 0 до 1

array([[0.38722526, 0.34836109],
       [0.17170121, 0.27909969],
       [0.99166216, 0.9631262 ],
       [0.29749684, 0.89847952]])

In [59]:
np.random.randint(-4, 8, size=(3, 3)) # случайные целые числа

array([[-4,  0,  2],
       [-2,  5, -1],
       [ 3, -1,  0]])

In [60]:
np.identity(5) # единичная матрица

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Осторожно при копировании (View vs Copy)

Когда вы берёте срез обычного списка (`list`) в питоне, создаётся его копия. В numpy срез возвращает **view (представление)** на те же данные в памяти! Это сделано для скорости работы с огромными объемами данных, чтобы не копировать их лишний раз.

In [22]:
arr = np.array([1, 2, 3])
view_arr = arr[0:2] # это не копия, это взгляд на те же данные
view_arr[0] = 99
arr # оригинальный массив тоже изменился!

array([99,  2,  3])

Если вам реально нужно скопировать данные, чтобы изменения не трогали оригинал, всегда используйте `.copy()`.

In [62]:
arr = np.array([1, 2, 3])
copy_arr = arr.copy()
copy_arr[0] = 99
arr # теперь оригинал в безопасности

array([1, 2, 3])

Если вам не нужен весь массив, а хочется быстро выдернуть несколько элементов в отдельный, безопасный «мини-срез», можно использовать Fancy Indexing (передать список нужных индексов в квадратных скобках)

В отличие от обычного среза через двоеточие, такой способ всегда принудительно создаёт копию в памяти

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Передаем список индексов вместо диапазона
sub_arr = arr[[0, 1, 2]]  # Выдернули первые 3 элемента
sub_arr[0] = 99

arr # Оригинал в полной безопасности!
# array([10, 20, 30, 40, 50])

### Математика

С numpy очень удобно делать математические операции сразу над всеми элементами `np.array`. Не нужно писать циклы `for`, это работает мгновенно.

In [63]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [64]:
a + 2

array([3, 4, 5, 6])

In [65]:
a * 2

array([2, 4, 6, 8])

In [66]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [67]:
a ** 2

array([ 1,  4,  9, 16])

Можно складывать `np.array` между собой (поэлементно).

In [68]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

И есть много встроенных математических функций.

In [69]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Статистика

В numpy встроены функции для поиска минимумов, максимумов и суммы. Часто мы хотим найти сумму не всего `np.array`, а по строкам или столбцам. Для этого используется аргумент `axis`.

In [24]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.min(stats)

np.int64(1)

In [72]:
np.max(stats, axis=1) # максимум в каждой строке

array([3, 6])

In [73]:
np.sum(stats, axis=0) # сумма по колонкам

array([5, 7, 9])

In [25]:
# TODO найдите среднее значение всего массива stats (сохраните в переменную mean_val)
mean_val = np.average(stats)

assert mean_val == 3.5

### Фильтрация данных (Булева маскировка)

Это **одна из самых важных** фичей Numpy (и Pandas в будущем). Мы можем легко отфильтровать данные по условию без всяких циклов `if`.

In [26]:
data = np.array([10, 20, 30, 40, 50, 60, 70])
# Допустим, мы хотим получить только числа больше 30

Сначала посмотрим, что вернет само условие:

In [76]:
data > 30

array([False, False, False,  True,  True,  True,  True])

Мы получили `np.array` из `True` и `False` (это и есть маска). А теперь передадим эту маску внутрь квадратных скобок `[]` оригинального `np.array`:

In [77]:
data[data > 30]

array([40, 50, 60, 70])

Можно комбинировать условия с помощью `&` (и) и `|` (или). **Важно:** каждое условие обязательно брать в скобки `()`!

In [78]:
data[(data > 20) & (data < 60)]

array([30, 40, 50])

In [30]:
# TODO отфильтруйте массив data, оставив только числа, которые делятся на 20 без остатка
filtered_data = data[data % 20 == 0]
filtered_data
assert np.array_equal(filtered_data, np.array([20, 40, 60]))

А если мы хотим не просто отфильтровать, а заменить значения по условию? Для этого отлично подходит `np.where(условие, значение_если_True, значение_если_False)`.

In [80]:
np.where(data > 30, 1, 0) # всё что больше 30 превращаем в 1, остальное в 0

array([0, 0, 0, 1, 1, 1, 1])

### Изменение формы (Reshape) и склеивание

Можно менять форму `np.array`, главное чтобы общее количество элементов оставалось тем же.

In [32]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
after = before.reshape((4, 2))
after


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
# TODO превратите np.array after обратно в вектор (одномерный массив) и сохраните в flat_array
flat_array = after.reshape(8)

assert flat_array.shape == (8,)

Можно склеивать `np.array` вместе по вертикали `vstack` или горизонтали `hstack`.

In [83]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])